# SPDX-FileCopyrightText: 2023 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
--- 
services: 
  nginx: 
    image: nginx
    ports: 
      - "7999:80"
  dynamodb: 
    container_name: dynamodb
    hostname: dynamodb.local.amazonaws.com
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -inMemory -sharedDb
    ports: 
      - "7998:8000"
  kinesis: 
    container_name: kinesis
    hostname: kinesis
    image: saidsef/aws-kinesis-local
    ports: 
      - "7997:4567" 
version: "3.8"